routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('admin/login','Admin\UsersController@login')->name('show_login');
Route::post('admin/login','Admin\UsersController@doLogin')->name('do_login');
Route::get('admin/logout','Admin\UsersController@logout')->name('logout');
//Auth::routes();



//Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin','namespace'=>'Admin', 'middleware' => 'admin'], function()
{
    Route::get('dashboard',
        function (){
            return view('admin.dashboard.index');
        }
    );

    // users
    Route::resource('users', 'UsersController');

    // users
    //Route::post('users/user/{user_id}', 'UsersController@update')->name('updateUser');

    Route::get('users/cars/{user_id}','usersController@userCars')->name('userCars');
    // cars
    Route::resource('cars', 'CarsController');
    Route::post('cars/car/{id}', 'CarsController@update')->name('updateCar');



    Route::resource('main_categories', 'MainCategoriesController');
    Route::post('main_categories/category/{id}', 'MainCategoriesController@update')->name('updateMC');

    Route::resource('categories', 'CategoriesController');
    Route::post('categories/category/{id}', 'CategoriesController@update')->name('updateC');


    Route::resource('cities', 'CitiesController');
    Route::post('cities/city/{id}', 'CitiesController@update')->name('updateCity');




    // accounts
    Route::resource('accounts', 'AccountsController');
    Route::resource('contacts', 'ContactsController');
    Route::resource('pays', 'PaysController');


});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Pay.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pay extends Model
{
    //
    protected $fillable = [

        'user_id',
        'image',
    ];


    public function user(){
        return $this->belongsTo('App\User','user_id','id');
    }

}

app/Http/Controllers/Admin/PaysController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Pay;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PaysController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $pays = Pay::paginate(50);
        return view('admin.pays.index')->with('pays',$pays);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function destroy($id)
    {
        //

        $pay = Pay::findOrFail($id);

        if($pay->delete()){
            session()->flash('success','تم المسح');
            return back();
        }
    }
}

app/Http/Controllers/PayController.php
<?php

namespace App\Http\Controllers;

use App\Pay;
use Illuminate\Http\Request;

class PayController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pay  $pay
     * @return \Illuminate\Http\Response
     */
    public function show(Pay $pay)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Pay  $pay
     * @return \Illuminate\Http\Response
     */
    public function edit(Pay $pay)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pay  $pay
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pay $pay)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pay  $pay
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pay $pay)
    {
        //
    }
}

resources/views/admin/pays/index.blade.php
@extends('admin.layouts.home')
@section('title')
عمليات الدفع
@endsection

@section('content')


@section('content')

    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">عمليات الدفع</h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="reload"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
كل عمليات الدفع         </div>

        <table class="table datatable-button-init-basic">
            <thead>
            <tr>
                <th> # </th>
                <th>الاسم </th>
                <th>صورة الدفع</th>
                <th>العمليات</th>
            </tr>
            </thead>
            <tbody>
            @foreach($pays as $key=>$item)
                <tr>
                    <td>{{$key+1}}</td>
                    <td>{{$item->user->name}}</td>
                    <td><img src="{{getImg($item->image)}}"/></td>
                    <td>
                        <a href="{{route('users.edit',
                        ['id'=>$item->user_id])}}" data-toggle="tooltip"
                           data-original-title="تعديل">
                            <i class="icon-pencil7 text-inverse" style="margin-left: 10px"></i> </a>

                        <a href="#" onclick="Delete({{$item->id}})" data-toggle="tooltip" data-original-title="حذف">
                            <i class="icon-trash text-inverse text-danger" style="margin-left: 10px"></i> </a>
                        {!!Form::open( ['route' => ['pays.destroy',$item->id] ,
                        'id'=>'delete-form'.$item->id, 'method' => 'Delete']) !!}
                        {!!Form::close() !!}
                    </td>

                </tr>
                <!-- Modal -->
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic initialization -->

    <div class="links">
        {{ $pays->links() }}
    </div>

    <script>
        function Delete(id) {
            var item_id=id;
            console.log(item_id);
            swal({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف  ؟",
                icon: "warning",
                buttons: ["الغاء", "موافق"],
                dangerMode: true,

            }).then(function(isConfirm){
                if(isConfirm){
                    document.getElementById('delete-form'+item_id).submit();
                }
                else{
                    swal("تم االإلفاء", "حذف القسم تم الغاؤه",'info',{buttons:'موافق'});
                }
            });
        }



    </script>

    <div class="row">
        <div id="container">
            <canvas id="canvas"></canvas>
        </div>

    </div>
@endsection