routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('admin/login','Admin\UsersController@login')->name('show_login');
Route::post('admin/login','Admin\UsersController@doLogin')->name('do_login');
Route::get('admin/logout','Admin\UsersController@logout')->name('logout');
//Auth::routes();



//Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin','namespace'=>'Admin', 'middleware' => 'admin'], function()
{
    Route::get('dashboard',
        function (){
            return view('admin.dashboard.index');
        }
    );

    // users
    Route::resource('users', 'UsersController');

    // users
    //Route::post('users/user/{user_id}', 'UsersController@update')->name('updateUser');

    Route::get('users/cars/{user_id}','usersController@userCars')->name('userCars');
    // cars
    Route::resource('cars', 'CarsController');
    Route::post('cars/car/{id}', 'CarsController@update')->name('updateCar');



    Route::resource('main_categories', 'MainCategoriesController');
    Route::post('main_categories/category/{id}', 'MainCategoriesController@update')->name('updateMC');

    Route::resource('categories', 'CategoriesController');
    Route::post('categories/category/{id}', 'CategoriesController@update')->name('updateC');


    Route::resource('cities', 'CitiesController');
    Route::post('cities/city/{id}', 'CitiesController@update')->name('updateCity');




    // accounts
    Route::resource('accounts', 'AccountsController');
    Route::resource('contacts', 'ContactsController');
    Route::resource('pays', 'PaysController');


});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/layouts/errors.blade.php
@if(Session::has('success'))
    <div class="alert  alert-styled-left alert-success" style="color: black">
        <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span class="sr-only">اغلاق</span></button>
        <span class="text-semibold"></span>عظيم !<a href="#" class="alert-link"> {{ Session::get('success') }} </a> .
    </div>
@endif

@if(Session::has('error'))

    <div class="alert bg-warning alert-styled-left">
        <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span class="sr-only">اغلاق</span></button>
        <span class="text-semibold"></span>عفواً !<a href="#" class="alert-link"> {{ Session::get('error') }} </a> .
    </div>
@endif

resources/views/admin/layouts/footer.blade.php
<!-- Footer -->
<div class="footer text-muted text-center">
    &copy; 2018. <a href="#">تم التطوير والبرمجة</a> بواسطة <a href="#" target="_blank">شركة فكرة للحلول البرمجية </a>
</div>
<!-- /footer -->

</div>
<!-- /content area -->

</div>
<!-- /main content -->

</div>
<!-- /page content -->
</div>
@stack('scripts')
</body>
</html>

resources/views/admin/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        لوحة تحكم موقع فاستر
        |
        @yield('title')</title>
    <!-- Global stylesheets -->
    <!--    Favicon-->
    <!-- Favicon -->
    <meta name="msapplication-TileColor" content="#F7630C">
    <meta name="msapplication-TileImage" content="{{asset('website/assets/ico/ms-icon-144x144.png')}}">
    <meta name="theme-color" content="#F7630C">
    <link href="https://fonts.googleapis.com/css?family=Cairo" rel="stylesheet">
    <link href="{{asset('admin/admin/assets/css/icons/icomoon/styles.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/admin/assets/css/bootstrap.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/admin/assets/css/core.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/admin/assets/css/components.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/admin/assets/css/extras/animate.min.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/admin/assets/css/colors.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/admin/assets/css/customized.css')}}" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->
@yield('header')
@stack('header')
<!-- Core JS files -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script type="text/javascript"
            src='https://maps.google.com/maps/api/js?sensor=false&libraries=places&key=AIzaSyBQ9fjKJMbJHN-Xs8zEOIIk6CApqefwMgQ'></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/plugins/loaders/pace.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/core/libraries/jquery.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/core/libraries/bootstrap.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/plugins/loaders/blockui.min.js')}}"></script>
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
{{-- <link href="{{asset('admin/assets/icon-picker/css/fontawesome-iconpicker.min.css')}}" rel="stylesheet">--}}
<!-- /core JS files -->

    <!-- Theme JS files -->
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/plugins/visualization/d3/d3.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/plugins/visualization/d3/d3_tooltip.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/plugins/forms/styling/switchery.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/plugins/forms/styling/uniform.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/plugins/forms/selects/bootstrap_multiselect.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/plugins/ui/moment/moment.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/plugins/pickers/daterangepicker.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/plugins/forms/selects/select2.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/plugins/pagination/bootpag.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/plugins/pagination/bs_pagination.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/plugins/pagination/datepaginator.min.js')}}"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    {{--  @include('sweet::alert')--}}
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/plugins/ui/nicescroll.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/core/app.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/admin/assets/js/pages/components_pagination.js')}}"></script>
    {{--<script type="text/javascript" src="{{asset('admin/assets/js/pages/layout_fixed_custom.js')}}"></script>--}}
    @yield('script')

</head>

<body>

resources/views/admin/layouts/home.blade.php
@extends('admin.layouts.header')
@yield('title')
@include('admin.layouts.nav')
@include('admin.layouts.errors')
@yield('content')
@include('admin.layouts.footer')

resources/views/admin/layouts/nav.blade.php
<!-- Main navbar -->
<div class="navbar navbar-inverse">
    <div class="navbar-header">
        {{--<a class="navbar-brand" href="/dashboard"><img src="/admin/assets/images/logo.png" alt=""></a>--}}
        <a class="navbar-brand" href="{{url('/admin/dashboard')}}">
            {{--        <img src="{{asset('admin/assets/images/logo.png')}}" class="position-left" alt="">  --}}
        </a>

        <ul class="nav navbar-nav visible-xs-block">
            <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
            <li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
        </ul>
    </div>

    <div class="navbar-collapse collapse" id="navbar-mobile">
        <ul class="nav navbar-nav">
            <li><a class="sidebar-control sidebar-main-toggle hidden-xs"><i class="icon-paragraph-justify3"></i></a></li>

        </ul>

        {{--<p class="navbar-text"><span class="label bg-success">متصل اﻵن</span></p>--}}

        <ul class="nav navbar-nav navbar-right">

            {{--<li class="dropdown language-switch">--}}
            {{--<a class="dropdown-toggle" data-toggle="dropdown">--}}
            {{--<img src="{{asset('admin/assets/images/flags/sa.png')}}" class="position-left" alt="">--}}
            {{--عربي--}}
            {{--</a>--}}
            {{--</li>--}}

            {{--      <li class=" dropdown notifications-wrapper">--}}
            {{--        <a href="#" data-toggle="dropdown" class="btn btn-link btn-float has-text">--}}
            {{--          <i class="icon-earth text-primary"></i>--}}
            {{--          <span class="noti-badge">{{auth()->user()->unreadNotifications()->whereType('App\Notifications\CartNotification')->count()}}</span>--}}
            {{--        </a>--}}
            {{--        <ul class="dropdown-menu animated fadeInUp the-notifications-wrapper">--}}
            {{--            @foreach(auth()->user()->unreadNotifications()->whereType('App\Notifications\CartNotification')->orderBy('id','desc')->get() as $notification)--}}
            {{--          <li>--}}
            {{--            تم اضافه عربه جديده للمشاهده--}}
            {{--            <a href="{{route('admin.cart-items.show',$notification->data['cart_id'])}}" class="makeAsRead" data-id="{{$notification->id}}">--}}
            {{--              اضغط هنا--}}
            {{--            </a>--}}
            {{--          </li>--}}
            {{--                @endforeach--}}
            {{--            <div class="fetchReaded">--}}

            {{--            </div>--}}
            {{--                <li class="read-all-notis">--}}
            {{--                    <a href="javascript:" class="readedNotifications">مشاهده كل الاشعارات</a>--}}
            {{--                </li>--}}
            {{--        </ul>--}}
            {{--      </li>--}}

            <li class="dropdown dropdown-user">
                <a class="dropdown-toggle" data-toggle="dropdown">
                    <span>#</span>
                    <i class="caret"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="{{route('logout')}}"><i class="icon-switch2"></i> تسجيل خروج</a></li>
                </ul>
            </li>




        </ul>
    </div>
</div>
<!-- /main navbar -->


<!-- Page container -->
<div class="page-container">

    <!-- Page content -->
    <div class="page-content">
        <!-- Main sidebar -->
        <div class="sidebar sidebar-main ">
            <div class="sidebar-content">

                <!-- User menu -->
                <div class="sidebar-user">
                    <div class="category-content">
                        <div class="media">
                            <a href="#" class="media-left">
                                <img src="" class="img-circle img-sm" alt="">
                            </a>

                            <div class="media-body">
                                <span class="media-heading text-semibold">#</span>
                                <div class="text-size-mini text-muted">
                                    <i class="icon-pin text-size-small"></i> مدير الموقع
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- /user menu -->

                <!-- Main navigation -->
                <div class="sidebar-category sidebar-category-visible">
                    <div class="category-content no-padding">


                        <ul class="navigation navigation-main navigation-accordion">


                            <!-- Main -->
                            <li class="navigation-header"><span>الاعدادات الرئيسية</span> <i class="icon-menu"
                                                                                             title="Main pages"></i></li>
                            <li class="{{(Request::is('dashboard') ? 'active' : '')}}"><a href="/admin/dashboard"><i
                                            class="icon-home4"></i> <span>الصفحة الرئيسية</span></a></li>


                            <li>
                                <a href="#"><i class="icon-users2"></i> <span>الاعضاء</span></a>
                                <ul>
                                    <li class="{{(Request::is('dashboard/users') ? 'active' : '')}}">
                                        <a
                                                href="{{route('users.index')}}"><i class="icon-list"></i> كل الاعضاء</a>
                                    </li>
                                    <li class="{{(Request::is('admin/users/create') ? 'active' : '')}}"><a
                                                href="{{route('users.create')}}"><i class="icon-add-to-list"></i> اضافة

                                            عضو جديد</a>
                                    </li>
                                </ul>
                            </li>

                            <li>
                                <a href="#"><i class="icon-add-to-list"></i> <span>الاقسام الرئيسية </span></a>
                                <ul>
                                    <li class="{{(Request::is('main_categories.index') ? 'active' : '')}}">
                                        <a
                                                href="{{route('main_categories.index')}}"><i class="icon-list"></i> كل الاقسام</a>
                                    </li>
                                    <li class="{{(Request::is('main_categories.create') ? 'active' : '')}}"><a
                                                href="{{route('main_categories.create')}}">
                                            <i class="icon-add-to-list"></i> اضافة قسم جديد</a>
                                    </li>
                                </ul>
                            </li>



                            <li>
                                <a href="#"><i class="icon-add"></i> <span>الاقسام الفرعية </span></a>
                                <ul>
                                    <li class="{{(Request::is('categories.index') ? 'active' : '')}}">
                                        <a
                                                href="{{route('categories.index')}}"><i class="icon-list"></i> كل الاقسام</a>
                                    </li>
                                    <li class="{{(Request::is('categories.create') ? 'active' : '')}}"><a
                                                href="{{route('categories.create')}}"><i class="icon-add-to-list"></i> اضافة قسم جديد</a>
                                    </li>
                                </ul>
                            </li>

                            <li>
                                <a href="#"><i class="icon-archive"></i> <span>المدن</span></a>
                                <ul>
                                    <li class="{{(Request::is('cities.index') ? 'active' : '')}}">
                                        <a
                                                href="{{route('cities.index')}}"><i class="icon-list"></i> كل المدن</a>
                                    </li>
                                    <li class="{{(Request::is('cities.create') ? 'active' : '')}}"><a
                                                href="{{route('cities.create')}}"><i class="icon-add-to-list"></i> اضافة مدينة جديدة</a>
                                    </li>
                                </ul>
                            </li>

                            <li>
                                <a href="#"><i class="icon-car2"></i> <span>العربات</span></a>
                                <ul>
                                    <li class="{{(Request::is('cars.index') ? 'active' : '')}}">
                                        <a
                                                href="{{route('cars.index')}}"><i class="icon-list"></i> كل العربات</a>
                                    </li>
                                    <li class="{{(Request::is('cars.create') ? 'active' : '')}}"><a
                                                href="{{route('cars.create')}}"><i class="icon-add-to-list"></i> اضافة عربه جديدة </a>
                                    </li>
                                </ul>
                            </li>


                            <li>
                                <a href="#"><i class="icon-car2"></i> <span>الحسابات</span></a>
                                <ul>
                                    <li class="{{(Request::is('accounts.index') ? 'active' : '')}}">
                                        <a
                                                href="{{route('accounts.index')}}">
                                            <i class="icon-list"></i> كل الحسابات</a>
                                    </li>
                                    <li class="{{(Request::is('accounts.create') ? 'active' : '')}}"><a
                                                href="{{route('accounts.create')}}">
                                            <i class="icon-add-to-list"></i> اضافة حساب جديد </a>
                                    </li>
                                </ul>
                            </li>

                            <li>
                                <a href="#"><i class="icon-car2"></i> <span>الدفع</span></a>
                                <ul>
                                    <li class="{{(Request::is('pays.index') ? 'active' : '')}}">
                                        <a
                                                href="{{route('pays.index')}}">
                                            <i class="icon-list"></i> كل عمليات الدفع</a>
                                    </li>

                                </ul>
                            </li>

                            <li>
                                <a href="#"><i class="icon-car2"></i> <span>الرسايل</span></a>
                                <ul>
                                    <li class="{{(Request::is('contacts.index') ? 'active' : '')}}">
                                        <a
                                                href="{{route('contacts.index')}}">
                                            <i class="icon-list"></i> كل الرسايل</a>
                                    </li>

                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- /main navigation -->

            </div>
        </div>
        <!-- /main sidebar -->
    <!-- Main content -->
        <div class="content-wrapper">
            <!-- Page header -->
            <div class="page-header page-header-default">
                <div class="page-header-content">
                    <div class="page-title">
                        <h4><a href="{{Session::get('_previous')['url']}}" >
                                <i class="icon-arrow-right6 position-left"></i></a> <span class="text-semibold">لوحة تحكم فاستر </span> - @yield('title')</h4>
                    </div>

                    <div class="heading-elements">
                        <div class="heading-btn-group">
                            <a href="{{asset('dashboard')}}" class="btn btn-link btn-float has-text"><i class="icon-bars-alt text-primary"></i><span>بعض الاحصائيات</span></a>
                            <a href="#" class="btn btn-link btn-float has-text"><i class="icon-users text-primary"></i> <span>أعضاء الاداره</span></a>
                        </div>

                    </div>
                </div>

                <div class="breadcrumb-line">
                    <ul class="breadcrumb">
                        <li><a href="{{asset('dashboard')}}"><i class="icon-home2 position-left"></i> لوحة التحكم</a></li>
                        <li class="active">@yield('title')</li>
                    </ul>
                </div>
            </div>
            <!-- /page header -->        <!-- Content area -->
            <div class="content">
            @include('admin.layouts.errors')